server:
  servlet:
    context-path: /solocraft
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://db-solocraft.cvcaku442512.us-east-1.rds.amazonaws.com:3306/solocraft
    username: mairyeduardo
    password: '200102eduardo'
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
