server:
  servlet:
    context-path: /solocraft
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/solocraft
    username: root
    password: '@fundatec'
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
